language: csharp
solution: name-sorter.sln
mono: none
install:
  - nuget restore name-sorter.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
  - cd ./name-sorter/name-sorter/
  - csc name-sorter.cs User.cs functions.cs
  - name-sorter ./unsorted-names-list.txt
